name:                               Run tests

on:
  pull_request:
    paths:
      - "**.php"
      - "phpunit.xml"
      - ".github/workflows/run-tests.yml"
      - "composer.lock"
      - "composer.json"

jobs:
    php-tests:
        runs-on:                    ${{ matrix.os }}

        strategy:
            matrix:
                php:                [8.3, 8.4]
                laravel:            [11.*, 12.*]
                dependency-version: [prefer-lowest, prefer-stable]
                os:                 [ubuntu-latest]
                include:
                    - laravel:      11.*
                      testbench:    9.*
                    - laravel:      12.*
                      testbench:    10.*

        name:                       P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name:                 Checkout code
              uses:                 actions/checkout@v2

            - name:                 Setup PHP
              uses:                 shivammathur/setup-php@v2
              with:
                  php-version:      ${{ matrix.php }}
                  extensions:       dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage:         pcov

            - name:                 Install dependencies
              run:                  |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            - name:               Execute tests
              run:                composer run-script test
